Develop
myeongjaeking/AddStringPOJO pull request #8
Opened 2024-12-31 10:11 UTC by myeongjaeking

2024-12-31 10:17 UTC, myeongjaeking reviewed
[Fix] CustomeSeparator 변경

2024-12-31 10:19 UTC, myeongjaeking commented on src/CustomSeparator.java
> +        newlineCustom(totalString);
[Refactor] 커스텀 구분자 추출 방법

2025-01-01 07:45 UTC, jjh75607 requested changes

2025-01-01 07:45 UTC, jjh75607 commented on addString.iml
>  </module>
이런 필요 없는 파일은 이그노어 파일 사용해서 커밋 되지 않도록 하면 좋겠습니다

2025-01-01 07:45 UTC, jjh75607 commented on src/Colon.java
> +    private String colon = ":";
private final static COLON = ":" 과 같이 상수로 치환하는게 더 좋을 거 같습니다

2025-01-01 07:45 UTC, jjh75607 commented on src/Colon.java
> +        colonChangePlus=totalString.replace(colon,"plus");
참신한 방법이긴 하지만 만약 -, *, / 와 같은 요구사항이 추가 되는 경우 거나, 구분자로 plus를 입력 한 경우는 어떻게 될까요?

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +    private String[] startEndString;
변수명이 너무 모호 한거 같습니다

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +    private int i;
customSeparatorExtract 메소드 에서만 사용하는거 같은데 필드로 빼둔 이유가 따로 있을까요

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +            startEndString[0].charAt(i);
startEndString[0]이 무엇인지 명확하지 않기 때문에 변경하는게 좋을 것 같습니다

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +        totalString = totalString.replace("\\n","\n");
이게 과연 필요한 행위일까요?

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +        this.startEndString = totalString.split("\n");
만약 필요하다고 하더라도 어차피 필드 변수의 값으로 넣어준다면 생성자에서 처리하면 되지않을까요?

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +    //문자열 시작이 "//"인지 참,거짓 반환
이런 누가보더라도 한번에 이해 할 수 있는 동작에 대한 주석은 필요하지 않다고 생각합니다

2025-01-01 07:45 UTC, jjh75607 commented on src/CustomSeparator.java
> +
이런 의미 없는 개행, 공백들은 ide의 자동 포맷팅 기능 이용해서 수정 하시면 좋을 것 같습니다

2025-01-01 07:45 UTC, jjh75607 commented on src/Main.java
> +        while (true){
계속해서 모든 객체를 새로 생성해야하는 이유가 따로 있을까요? 
동작이 같고, 어떤 상태를 포함하지 않는다면 정적으로 사용하는 게 좋아보입니다

2025-01-01 07:45 UTC, jjh75607 commented on src/Separator.java
> +    public String separatorChangePlusString(String addSeparator);
Colon과 Rest에서 같은 행위를 구현하는것으로 보이는데 상속 기능을 사용하는게 맞지 않을까요?

2025-01-01 07:45 UTC, jjh75607 commented on src/SumPlus.java
> +public class SumPlus {
클래스 이름이 의미를 제대로 전달하지 못 하고 있는거 같습니다

2025-01-01 07:45 UTC, jjh75607 commented on src/SumPlus.java
> +        sum =0;
이런 경우라면 메소드 내부에 선언 하는 경우가 더 좋지 않을까요

2025-01-01 07:45 UTC, jjh75607 commented on test/ColonTest.java
> +    @Test
@DisplayName 어노테이션을 사용해서 테스트가 무엇을 표현하고자 하는지 명확히 표현하면 좋겠습니다

2025-01-01 07:46 UTC, jjh75607 commented
리드미가 너무 간략화되어 작성되어있다고 생각합니다. 수정 해주시면 좋을거 같고
테스트가 검증 하는 부분이 너무 적은 케이스만 검증되고 있습니다. 다양한 케이스를 검증하고, 해피케이스 뿐만 아니라 예외 케이스들 또한 검증 해야 할 것 같습니다.
또한 패키지 구조를 하나도 나누지 않았고, 매직 넘버가 포함된 코드가 너무 많습니다

2025-01-01 07:50 UTC, jjh75607 commented
어떤 변수가 무엇을 하는지 명확하지 않은 부분도 너무 많고, 예외처리 케이스가 너무 적은 것 같습니다. 
만약 사용자가 유효치 않은 입력을 한다면?, 커스텀 구분자로 숫자를 입력한다면?, //\n안에 커스텀 구분자를 입력하지 않는 다면? 여러 예외 처리 케이스를 생각해서 구현 해주세요.
또한 너무 요구사항 자체만 구현 하려고 한 것 같습니다. 조금만 엇나가는 입력, 행위가 벌어지면 프로그램이 바로 멈출 것 같습니다. 
위의 코멘트들 유의 해서 다시 작성 하시면 되겠습니다.

2025-01-01 07:50 UTC, closed without merging